spring: 
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id:
            client-secret: 
            redirect-uri: http://localhost:8086/login/oauth2/code/google
            scope:
              - email
              - profile
